# Generated by Django 5.2.6 on 2025-10-05 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessinsight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_insights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessmetrics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashflowdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flow_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['user', 'is_active'], name='alert_rules_user_id_362e53_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['alert_type'], name='alert_rules_alert_t_8d302b_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['last_triggered'], name='alert_rules_last_tr_af980f_idx'),
        ),
        migrations.AddIndex(
            model_name='businessinsight',
            index=models.Index(fields=['user', 'insight_type'], name='business_in_user_id_bf9841_idx'),
        ),
        migrations.AddIndex(
            model_name='businessinsight',
            index=models.Index(fields=['priority'], name='business_in_priorit_c026c5_idx'),
        ),
        migrations.AddIndex(
            model_name='businessinsight',
            index=models.Index(fields=['is_viewed'], name='business_in_is_view_d7e5c7_idx'),
        ),
        migrations.AddIndex(
            model_name='businessinsight',
            index=models.Index(fields=['confidence_score'], name='business_in_confide_1313b1_idx'),
        ),
        migrations.AddIndex(
            model_name='businessinsight',
            index=models.Index(fields=['expires_at'], name='business_in_expires_d16fb2_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmetrics',
            index=models.Index(fields=['user', 'period_type'], name='business_me_user_id_68e938_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmetrics',
            index=models.Index(fields=['period_start', 'period_end'], name='business_me_period__2505fd_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmetrics',
            index=models.Index(fields=['total_sales_amount'], name='business_me_total_s_3156c4_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmetrics',
            index=models.Index(fields=['performance_score'], name='business_me_perform_37ab54_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='businessmetrics',
            unique_together={('user', 'period_type', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='cashflowdata',
            index=models.Index(fields=['user', 'flow_date'], name='cash_flow_d_user_id_d19c31_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflowdata',
            index=models.Index(fields=['flow_type', 'category'], name='cash_flow_d_flow_ty_1bd3ef_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflowdata',
            index=models.Index(fields=['is_predicted'], name='cash_flow_d_is_pred_5bf70c_idx'),
        ),
    ]
