# Generated by Django 5.2.6 on 2025-10-05 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_categorization', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryprediction',
            name='actual_category',
            field=models.ForeignKey(blank=True, help_text='Category chosen by user (for training)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual_classifications', to='inventory.productcategory'),
        ),
        migrations.AddField(
            model_name='categoryprediction',
            name='predicted_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='inventory.productcategory'),
        ),
    ]
