# Generated by Django 5.2.6 on 2025-10-05 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_categorization', '0002_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryprediction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_predictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='modelperformance',
            index=models.Index(fields=['model_version'], name='model_perfo_model_v_4d63e8_idx'),
        ),
        migrations.AddIndex(
            model_name='modelperformance',
            index=models.Index(fields=['model_type'], name='model_perfo_model_t_193876_idx'),
        ),
        migrations.AddIndex(
            model_name='modelperformance',
            index=models.Index(fields=['accuracy'], name='model_perfo_accurac_23c22a_idx'),
        ),
        migrations.AddIndex(
            model_name='modelperformance',
            index=models.Index(fields=['is_deployed'], name='model_perfo_is_depl_e9119a_idx'),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_data', to='inventory.productcategory'),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='contributed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_training_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='categoryprediction',
            index=models.Index(fields=['user', 'status'], name='category_pr_user_id_e97300_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryprediction',
            index=models.Index(fields=['predicted_category'], name='category_pr_predict_297a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryprediction',
            index=models.Index(fields=['confidence_score'], name='category_pr_confide_a1eba5_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryprediction',
            index=models.Index(fields=['model_version'], name='category_pr_model_v_1eb509_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingdata',
            index=models.Index(fields=['category', 'status'], name='training_da_categor_339fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingdata',
            index=models.Index(fields=['source'], name='training_da_source_41cf9d_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingdata',
            index=models.Index(fields=['language'], name='training_da_languag_57a05a_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingdata',
            index=models.Index(fields=['is_validated'], name='training_da_is_vali_1e5b6c_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingdata',
            index=models.Index(fields=['validation_score'], name='training_da_validat_a82c4c_idx'),
        ),
    ]
