# Generated by Django 5.2.6 on 2025-10-05 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('savings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='savings_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='savings.savingsaccount'),
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_savings_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='savings_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='savings.savingsaccount'),
        ),
        migrations.AddIndex(
            model_name='savingsaccount',
            index=models.Index(fields=['user', 'status'], name='savings_acc_user_id_eeb268_idx'),
        ),
        migrations.AddIndex(
            model_name='savingsaccount',
            index=models.Index(fields=['account_number'], name='savings_acc_account_fc7e98_idx'),
        ),
        migrations.AddIndex(
            model_name='savingsaccount',
            index=models.Index(fields=['account_type'], name='savings_acc_account_0d85d7_idx'),
        ),
        migrations.AddIndex(
            model_name='savingsgoal',
            index=models.Index(fields=['savings_account', 'status'], name='savings_goa_savings_e6e8dc_idx'),
        ),
        migrations.AddIndex(
            model_name='savingsgoal',
            index=models.Index(fields=['target_date'], name='savings_goa_target__9ae66f_idx'),
        ),
        migrations.AddIndex(
            model_name='savingstransaction',
            index=models.Index(fields=['savings_account', 'transaction_date'], name='savings_tra_savings_3f075c_idx'),
        ),
        migrations.AddIndex(
            model_name='savingstransaction',
            index=models.Index(fields=['transaction_reference'], name='savings_tra_transac_3a4596_idx'),
        ),
        migrations.AddIndex(
            model_name='savingstransaction',
            index=models.Index(fields=['transaction_type'], name='savings_tra_transac_728cdd_idx'),
        ),
        migrations.AddIndex(
            model_name='savingstransaction',
            index=models.Index(fields=['source_transaction_id'], name='savings_tra_source__895560_idx'),
        ),
    ]
