# Generated by Django 5.2.7 on 2025-10-15 14:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
        ("transactions", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("sales", "Sales"),
                            ("purchase", "Purchase"),
                            ("expense", "Expense"),
                            ("inventory_in", "Inventory Inward"),
                            ("inventory_out", "Inventory Outward"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "remark_keywords",
                    models.TextField(
                        blank=True,
                        help_text="Keywords for auto-detection: indomie,milo,purchase",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "transaction_categories",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-transaction_date"]},
        ),
        migrations.AlterModelOptions(
            name="transactionitem",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="transaction_referen_dda4a8_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="transaction_transac_ddda52_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="transaction_payment_afdbde_idx",
        ),
        migrations.RemoveIndex(
            model_name="transactionitem",
            name="transaction_transac_163e28_idx",
        ),
        migrations.RemoveIndex(
            model_name="transactionitem",
            name="transaction_product_762b50_idx",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="customer_name",
            new_name="counterparty_name",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="customer_phone",
            new_name="counterparty_phone",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="auto_save_applied",
            new_name="journal_entry_created",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="ai_category",
            new_name="journal_entry_reference",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="ai_confidence",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="change_amount",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="customer_email",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="pos_device_serial",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="pos_transaction_id",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="reference_number",
        ),
        migrations.RemoveField(
            model_name="transactionitem",
            name="discount_amount",
        ),
        migrations.RemoveField(
            model_name="transactionitem",
            name="product_name",
        ),
        migrations.AddField(
            model_name="transaction",
            name="flow_direction",
            field=models.CharField(
                choices=[
                    ("inward", "Inward (Stock/Money In)"),
                    ("outward", "Outward (Stock/Money Out)"),
                ],
                default="inward",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="remark_parsed_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_remark",
            field=models.TextField(
                blank=True, help_text='Bank remark: "Transfer for Indomie purchase"'
            ),
        ),
        migrations.AddField(
            model_name="transactionitem",
            name="item_name",
            field=models.CharField(default="items", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="auto_save_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("pos", "POS Card"),
                    ("bank_transfer", "Bank Transfer"),
                    ("mobile_money", "Mobile Money"),
                    ("credit", "Credit"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("sale", "Sale"),
                    ("purchase", "Purchase"),
                    ("return", "Return"),
                    ("adjustment", "Adjustment"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="line_total",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.product",
            ),
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="transactions.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="unit_cost",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_category",
            field=models.ForeignKey(
                default=uuid.uuid4,
                help_text="Select category FIRST",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="transactions.transactioncategory",
            ),
        ),
    ]
