# Generated by Django 5.2.6 on 2025-10-05 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loan_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='loans.loanproduct'),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_repayments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['borrower', 'status'], name='loans_borrowe_6654de_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['loan_number'], name='loans_loan_nu_a48674_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='loans_status_9049a0_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['days_past_due'], name='loans_days_pa_7119d4_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['disbursed_date'], name='loans_disburs_f0cd27_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrepayment',
            index=models.Index(fields=['loan', 'payment_date'], name='loan_repaym_loan_id_abc9c3_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrepayment',
            index=models.Index(fields=['payment_reference'], name='loan_repaym_payment_8cbd28_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrepayment',
            index=models.Index(fields=['due_date'], name='loan_repaym_due_dat_cdbc19_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrepayment',
            index=models.Index(fields=['status'], name='loan_repaym_status_3c4ef3_idx'),
        ),
    ]
